# **Use python numpy! ... and take data science by storm**

### read csv

In [202]:
import pandas as pd 
test_pandas_dataframe = pd.read_csv("./Bikeshare_Scooter_Systems.csv") 
print('read successfully')

read successfully


### import numpy

In [201]:
import numpy as np

### get numeric array

In [203]:
test_pandas_dataframe_numeric = test_pandas_dataframe.loc[0:10, 'year':'dockid']
test_numpy_array = test_pandas_dataframe_numeric.to_numpy()
print(test_numpy_array)

[[2015 '63']
 [2015 '37']
 [2015 '59']
 [2015 '42']
 [2015 '75']
 [2015 '39']
 [2015 '27']
 [2015 '11']
 [2015 '7']
 [2015 '56']
 [2015 '12']]


### numpy manipulation array operations

In [204]:
print(type(test_numpy_array))
print(test_numpy_array.dtype)
print(test_numpy_array.ndim)
print(test_numpy_array.size)
print(test_numpy_array.shape)

<class 'numpy.ndarray'>
object
2
22
(11, 2)


In [205]:

print("a[0]:" , test_numpy_array[0])
print("a[0]:" , test_numpy_array[1][0])

test_numpy_array[1][0] = 2016
print(test_numpy_array[1][0])


a[0]: [2015 '63']
a[0]: 2015
2016


In [206]:
sliced_test_numpy_array_1 = test_numpy_array[0:1]
print(sliced_test_numpy_array_1)

sliced_test_numpy_array_2 = test_pandas_dataframe_numeric['dockid'].to_numpy()[1:5:1]
print(sliced_test_numpy_array_2)

sliced_test_numpy_array_3 = test_pandas_dataframe_numeric['year'].to_numpy()[1:5:1]
print(sliced_test_numpy_array_3)


[[2015 '63']]
['37' '59' '42' '75']
[2015 2015 2015 2015]


### numpy statistic array operations

In [207]:
sliced_test_numpy_array_2 = sliced_test_numpy_array_2.astype(int)
print(sliced_test_numpy_array_2.mean())
print(sliced_test_numpy_array_2.std())
print(sliced_test_numpy_array_2.max())
print(sliced_test_numpy_array_2.min())

53.25
14.972892172189045
75
37


### numpy calculation array operation

In [208]:
print(sliced_test_numpy_array_2+1)
print(np.add(sliced_test_numpy_array_2,sliced_test_numpy_array_3))
print(np.subtract(sliced_test_numpy_array_2,sliced_test_numpy_array_3))
print(np.multiply(sliced_test_numpy_array_2,sliced_test_numpy_array_3))
print(np.divide(sliced_test_numpy_array_2,sliced_test_numpy_array_3))
print(np.dot(sliced_test_numpy_array_2,sliced_test_numpy_array_3))

[38 60 43 76]
[2052 2074 2057 2090]
[-1978 -1956 -1973 -1940]
[ 74555 118885  84630 151125]
[0.01836228 0.0292804  0.02084367 0.03722084]
429195


### mathematical functions

In [211]:
print(np.pi)
print(np.sin(1))
print(np.linspace(-2,2,num=5))
sinus = np.sin(np.linspace(0,2*np.pi,num=100))
#plt.plot(sinus)


3.141592653589793
0.8414709848078965
[-2. -1.  0.  1.  2.]
